name: Build and Release AppImages

on:
  workflow_dispatch:
  push:
    paths:
      - 'Scripts/**'
      - 'HyprUpld.png'
      - 'compile.sh'
      - 'install_scripts.sh'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for changelog generation

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget fuse build-essential cmake \
                                  libglib2.0-dev libcairo2-dev libpango1.0-dev \
                                  imagemagick zip

      - name: Set Executable Permissions
        run: |
          chmod +x compile.sh install_scripts.sh

      - name: Build AppImage
        run: ./compile.sh

      - name: Set Permissions for Generated Files
        run: |
          chmod +x Compiled/*.AppImage
          chmod +x Scripts/*.sh

      - name: Package Release Artifacts
        run: |
          mkdir -p release_package/Compiled
          cp Compiled/*.AppImage release_package/Compiled/
          cp install_scripts.sh release_package/
          cp -r Scripts/ release_package/
          cd release_package
          zip -r ../hypr_installer.zip .

      - name: Retrieve Short Git SHA
        id: slug
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 --always HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "changelog=Initial release" >> $GITHUB_OUTPUT
          else
            CHANGES=$(git log --pretty=format:"* %s (%h)" $PREVIOUS_TAG..HEAD)
            echo "changelog<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.slug.outputs.sha_short }}
          name: Release ${{ steps.slug.outputs.sha_short }}
          draft: false
          prerelease: false
          files: |
            Compiled/*.AppImage
            Scripts/*.sh
            hypr_installer.zip
          body: |
            ${{ steps.changelog.outputs.changelog }}

            ### Included in this release:
            - Individual AppImages (Compiled directory)
            - Individual script files (Scripts directory)
            - Complete installation package (hypr_installer.zip) including all AppImages, scripts, and the installation script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
